
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadorSintactico;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int TIMES = 14;
  public static final int MOD = 16;
  public static final int AND = 23;
  public static final int SEMICOLON = 28;
  public static final int ELSE = 8;
  public static final int PLUS = 12;
  public static final int Numero = 31;
  public static final int RPAREN = 27;
  public static final int OR = 24;
  public static final int LESS_EQUAL = 18;
  public static final int THEN = 7;
  public static final int GREATER_THAN = 22;
  public static final int NOT = 25;
  public static final int END = 9;
  public static final int GREATER_EQUAL = 19;
  public static final int Identificador = 30;
  public static final int IF = 6;
  public static final int LPAREN = 26;
  public static final int BOOLEAN = 5;
  public static final int EQUALS = 20;
  public static final int STRING = 4;
  public static final int COMMA = 29;
  public static final int EOF = 0;
  public static final int DIVIDE = 15;
  public static final int LESS_THAN = 21;
  public static final int MINUS = 13;
  public static final int NOT_EQUALS = 17;
  public static final int error = 1;
  public static final int INTEGER = 3;
  public static final int DIM = 2;
  public static final int FOR = 10;
  public static final int NEXT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DIM",
  "INTEGER",
  "STRING",
  "BOOLEAN",
  "IF",
  "THEN",
  "ELSE",
  "END",
  "FOR",
  "NEXT",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "MOD",
  "NOT_EQUALS",
  "LESS_EQUAL",
  "GREATER_EQUAL",
  "EQUALS",
  "LESS_THAN",
  "GREATER_THAN",
  "AND",
  "OR",
  "NOT",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "Identificador",
  "Numero"
  };
}

